name: Build Filmes Gratis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: instalação de dependências
      run: | 
        cd freemovies
        npm install
        
    - name: instalação do jscpd
      run: | 
        cd freemovies
        npm install -g jscpd

    - name: execução do jscpd
      run: | 
        cd freemovies
        npx jscpd "./src"
        if [ $? -ne 0 ]; then
          echo "Código duplicado encontrado!"
          exit 1
        fi

    - name: Prettier 
      run: | 
        cd freemovies
        npx prettier . --check

    - name: Build do projeto 
      run: | 
        cd freemovies
        npm run build

